Fix NicoNico sendEventin developer.js
akashic-games/akashic-sandbox pull request #159
Opened 2021-02-03 07:25 UTC by ShinobuTakahashi

## 概要

開発ツールの NicoNico タブの「ニコニコ新市場のセッションパラメータを送る」 と Events タブの「ゲーム開始時にEventを自動送信」にチェックが入っている場合で 2つのメッセージイベントの type が `start` の時にエラーとなっていた。
(「ニコニコ新市場のセッションパラメータを送る」 は内部で type: "start" となっていた)

2つ start が送信されるため、_bootstrap.js の `scene.onMessage` トリガー内で2回 コンテンツを起動し、`g.game.pushScene()` でコンテンツのシーンが2つpushされるため `DefarultLoadingScene` も 2つ追加され、シーン切替えで `DefarultLoadingScene` が destroy されてしまい DefarultLoadingScene が参照していた `Trigger#_handlers` が null となりエラーとなっていた。 

*修正*

「ニコニコ新市場のセッションパラメータを送る」で内部で送っているパラメータの type を `start` から `dummy` へ修正し、コンテンツのシーンが2つ追加されないようにした。

2021-02-03 11:15 UTC, xnv commented
ええと、 `"dummy"` にしちゃうと `"start"` であることを仮定しているコンテンツの動作がおかしくなりませんか。

どちらかというと、

- a)「ニコニコ新市場のセッションパラメータを送る」
- b) Events タブの「ゲーム開始時にEventを自動送信」

の二つがかち合ってるのがまずいように思います。(b) の新市場特化版が (a) という趣なので。

悩ましいですが、(a), (b) それぞれを有効にする操作の時にお互いをチェックして、両方有効にはできないようにしませんか。また異常系に備えて「両方有効になっていたら console.error() して (b) を無視する」動作にしたいです。

2021-02-03 11:16 UTC, xnv requested changes
ええと、 `"dummy"` にしちゃうと `"start"` であることを仮定しているコンテンツの動作がおかしくなりませんか。

どちらかというと、

- a)「ニコニコ新市場のセッションパラメータを送る」
- b) Events タブの「ゲーム開始時にEventを自動送信」

の二つがかち合ってるのがまずいように思います。(b) の新市場特化版が (a) という趣なので。

悩ましいですが、(a), (b) それぞれを有効にする操作の時にお互いをチェックして、両方有効にはできないようにしませんか。また異常系に備えて「両方有効になっていたら console.error() して (b) を無視する」動作にしたいです。

2021-02-04 04:37 UTC, ShinobuTakahashi commented
>a)「ニコニコ新市場のセッションパラメータを送る」
b) Events タブの「ゲーム開始時にEventを自動送信」

a, b の有効/無効の変更時に、a, b どちらかのみ有効になるよう修正しました。また、a, b どちらも有効の場合には、connsole.error() でエラーメッセージを出力し、b を無効にして実行するよう修正しました。

2021-02-05 03:44 UTC, xnv requested changes

2021-02-05 03:44 UTC, xnv commented on engine-src/v2/js/developer.js
> +				config.autoSendEvents = false; // Events タブのゲーム開始時にEventを自動送信を無効化
ええと、黙って変えるとユーザにとって予期しない動作になってしまい、それはそれで不具合に見えると思います ("変えてないオプションが勝手に変更される" 不具合) 。なので UI 上で「有効にすると、〜タブの "〜" 機能は無効になります」といった説明をつけたいです。

また実際に無効にするこの箇所でも、もしそれで動作が変化する場合 (たとえばこの箇所なら `autoSendEvents` が `true` で、実際送信されるイベントの入力欄も空でない場合) は、ポップアップ (エラー表示に使っているもの) で「〜を無効にしました」とユーザに提示したいです。

2021-02-05 03:44 UTC, xnv commented on engine-src/v1/js/developer.js
> +		config.sendsSessionParameter = false
これこの値を変えると何かのタイミングで (`saveConfig()` されて) この状態で保存されてしまいませんか？　「一度でも `isIchibaContent` でないコンテンツを起動するとオプションが無効になるので、また手で有効にせねばならない」という挙動は嬉しくないように思います。

 `config` を上書きするのではなく、 `sendsSessionParameter` を参照する条件分岐の方を、 `isIchibaContent` も参照するような条件にするのはどうでしょうか。

2021-02-08 04:45 UTC, ShinobuTakahashi commented on engine-src/v2/js/developer.js
> +				config.autoSendEvents = false; // Events タブのゲーム開始時にEventを自動送信を無効化
ありがとうございます。UI 上に説明文追加しました。また、片方のチェックを無効にする場合にポップアップでメッセージを表示するよう修正しました。(ポップアップはタイトル等表示せず、メッセージのみ表示するようにしています。)
ポップアップ表示に合わせ、両方チェックされていた場合にconsole.log で出力していた箇所をポップアップに修正しました。

2021-02-08 04:45 UTC, ShinobuTakahashi commented on engine-src/v1/js/developer.js
> +		config.sendsSessionParameter = false
仰る通りです。`sendsSessionParameter` を参照する条件分岐箇所で `isIchibaContent` も参照するように修正しました。

2021-02-10 05:05 UTC, xnv requested changes

2021-02-10 05:05 UTC, xnv commented on engine-src/v1/js/developer.js
> +		dialogBody: true,
`dialogTitle` は string なのに `dialogBody` は boolean というのは直感に反するような。 文字列にして、デフォルト値を「Developer ツールでエラーを確認してください」みたいな既存のやつにするのはどうでしょうか。

2021-02-10 05:05 UTC, xnv commented on engine-src/v1/js/developer.js
> +			message: `Events タブのゲーム開始時にEventを自動送信が有効になっています。無効にして実行します。`,
条件  (二つのフラグを見ている) とメッセージ (一つの条件にしか言及していない) が対応していないと思います。このパスに入る人がこの条件を知っているとは全く思えないので、エラーメッセージで何が起きているのか・何をすればいいのか理解できるようにしたいです。

別コメントのとおり、 "body" 部分として「〜と〜を両方同時に有効にすることはできません。〜を無効にして実行します」と表示するのはどうでしょうか。

2021-02-10 05:05 UTC, xnv commented on engine-src/v3/js/developer.js
>  				config.autoSendEvents = false; // Events タブのゲーム開始時にEventを自動送信を無効化
実害はなさそうですが、関係がわかりやすいので、この実際の無効化も if 文の中に入れませんか。

2021-02-10 06:25 UTC, ShinobuTakahashi commented on engine-src/v3/js/developer.js
>  				config.autoSendEvents = false; // Events タブのゲーム開始時にEventを自動送信を無効化
修正しました。

2021-02-10 06:25 UTC, ShinobuTakahashi commented on engine-src/v1/js/developer.js
> +		dialogBody: true,
仰る通りです。 `dialogBody` を`string` にし、デフォルト値を設定するよう修正しました。

2021-02-10 06:25 UTC, ShinobuTakahashi commented on engine-src/v1/js/developer.js
> +			message: `Events タブのゲーム開始時にEventを自動送信が有効になっています。無効にして実行します。`,
ありがとうございます。エラーメッセージを「〜と〜を両方同時に有効にすることはできません。〜を無効にして実行します」の形式に修正しました。
body 部分は、`Developer Tool などでエラー内容を確認の上修正してください。` と表示される部分で(titile, message, body に別れています)、このメッセージのの場合は、DevTool 確認しても何も出てないので、空で表示されるよう修正しています。

2021-02-12 12:06 UTC, xnv approved these changes
コメントしていますが approved.

2021-02-12 12:06 UTC, xnv commented on engine-src/v3/js/developer.js
> +			message: `NicoNico タブの"セッションパラメータを送る"と Events タブの"ゲーム開始時にEventを自動送信"を両方同時に有効にすることはできません。Events タブの"ゲーム開始時にEventを自動送信"を無効にして実行します。`,
> Events タブの"ゲーム開始時にEventを自動送信"を無効にして実行します。

これ「無効にしました」としたいです。("無効にして実行する" のは、異常系で「両方有効になってしまっていた時」だけなので)

2021-02-12 12:06 UTC, xnv commented on engine-src/v3/js/developer.js
> +						message: `Events タブの "ゲーム開始時にEventを自動送信" と NicoNico タブの "セッションパラメータを送る" を両方同時に有効にすることはできません。NicoNicoタブの "セッションパラメータを送る" 機能を無効にして実行します。`,
こちらも「無効にしました」にしたいです。

2021-02-15 02:29 UTC, ShinobuTakahashi commented on engine-src/v3/js/developer.js
> +			message: `NicoNico タブの"セッションパラメータを送る"と Events タブの"ゲーム開始時にEventを自動送信"を両方同時に有効にすることはできません。Events タブの"ゲーム開始時にEventを自動送信"を無効にして実行します。`,
ありがとうございます。こちら修正しました。

2021-02-15 02:29 UTC, ShinobuTakahashi commented on engine-src/v3/js/developer.js
> +						message: `Events タブの "ゲーム開始時にEventを自動送信" と NicoNico タブの "セッションパラメータを送る" を両方同時に有効にすることはできません。NicoNicoタブの "セッションパラメータを送る" 機能を無効にして実行します。`,
こちらも修正しました。

2021-02-16 03:33 UTC, merged